import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
import joblib

def train_predictive_model():
    print("Loading extracted features and labels...")
    
    # 1. Load the data generated by the pipeline script
    try:
        X = pd.read_csv("extracted_features.csv")
        y = np.load("labels.npy")
    except FileNotFoundError:
        print("Error: Could not find the data files. Please run the feature extraction pipeline first.")
        return

    # 2. Split into Training (80%) and Testing (20%) sets
    # I set a random_state so the results are reproducible for my GitHub README
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    print(f"Training Data Shape: {X_train.shape}")
    print(f"Testing Data Shape: {X_test.shape}")
    
    # 3. Initialize and train the Decision Tree Model
    # Limit max_depth to keep the model size small for future TinyML deployment
    print("\nTraining the Decision Tree Classifier...")
    model = DecisionTreeClassifier(max_depth=5, random_state=42)
    model.fit(X_train, y_train)
    
    # 4. Evaluate the Model
    print("\nEvaluating Model Performance on Test Data:")
    y_pred = model.predict(X_test)
    
    print("\nConfusion Matrix (Healthy vs. Failing):")
    print(confusion_matrix(y_test, y_pred))
    
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=["Healthy (0)", "Failing (1)"]))
    
    # 5. Save the trained model
    joblib.dump(model, "predictive_maintenance_model.pkl")
    print("\nModel saved successfully as 'predictive_maintenance_model.pkl'")

if __name__ == "__main__":
    train_predictive_model()